"use client";
import { FormEvent, useEffect, useState } from "react";
type Loan = { id:string; name:string; originalAmount:number; outstandingAmount:number|null; interestRate:number|null; monthlyPayment:number|null; startDate:string|null; endDate:string|null; principalPaid:number; interestPaid:number };
const money=(v:number|null)=>v==null?"—":`${v.toLocaleString("he-IL",{maximumFractionDigits:0})} ₪`;
export default function Loans(){ const [loans,setLoans]=useState<Loan[]>([]); const [form,setForm]=useState({name:"",originalAmount:"",outstandingAmount:"",interestRate:"",monthlyPayment:"",startDate:"",endDate:""}); const [error,setError]=useState("");
 async function load(){try{const r=await fetch("/api/loans",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"שגיאה");setLoans(b);}catch(e){setError(e instanceof Error?e.message:"שגיאה");}}
 useEffect(()=>{load()},[]);
 async function add(e:FormEvent){e.preventDefault();setError("");try{const r=await fetch("/api/loans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,originalAmount:Number(form.originalAmount),outstandingAmount:form.outstandingAmount?Number(form.outstandingAmount):null,interestRate:form.interestRate?Number(form.interestRate):null,monthlyPayment:form.monthlyPayment?Number(form.monthlyPayment):null,startDate:form.startDate||null,endDate:form.endDate||null})});const b=await r.json();if(!r.ok)throw new Error(b.error||"לא ניתן להוסיף");setForm({name:"",originalAmount:"",outstandingAmount:"",interestRate:"",monthlyPayment:"",startDate:"",endDate:""});load();}catch(e){setError(e instanceof Error?e.message:"שגיאה");}}
 const total=loans.reduce((s,l)=>s+(l.outstandingAmount||0),0), monthly=loans.reduce((s,l)=>s+(l.monthlyPayment||0),0);
 return <main className="page-shell" dir="rtl"><div className="page-header"><div><p className="eyebrow">התחייבויות</p><h1>הלוואות</h1><p>רואים כמה נשאר, כמה מחזירים כל חודש וכמה מהתשלומים הוא ריבית.</p></div></div>{error&&<div className="error-banner">{error}</div>}<section className="metrics-grid"><article className="metric-card"><span>יתרת חוב</span><strong>{money(total)}</strong></article><article className="metric-card"><span>החזר חודשי</span><strong>{money(monthly)}</strong></article><article className="metric-card"><span>מספר הלוואות</span><strong>{loans.length}</strong></article></section><section className="content-grid"><div className="card"><div className="card-header"><div><h2>ההלוואות שלי</h2><p>קרן ההלוואה אינה הוצאה צרכנית; הריבית כן.</p></div></div><div className="stack">{loans.map(l=>{const progress=l.originalAmount?Math.min(100,Math.max(0,((l.originalAmount-(l.outstandingAmount??l.originalAmount))/l.originalAmount)*100)):0;return <div className="fund-row" key={l.id}><div className="fund-main"><strong>{l.name}</strong><small>נשאר {money(l.outstandingAmount)} · החזר {money(l.monthlyPayment)} · ריבית {l.interestRate==null?"—":`${l.interestRate}%`}</small><div className="progress-track"><div className="progress-fill" style={{width:`${progress}%`}}/></div><small>שולם קרן: {money(l.principalPaid)} · ריבית ששולמה: {money(l.interestPaid)}</small></div></div>})}</div></div><div className="card"><div className="card-header"><div><h2>הוספת הלוואה</h2><p>הזינו את הנתונים הידועים לכם; אפשר להשלים בהמשך.</p></div></div><form className="form-grid" onSubmit={add}><label>שם<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required placeholder="משכנתא / הלוואה"/></label><label>סכום מקורי<input type="number" min="1" value={form.originalAmount} onChange={e=>setForm({...form,originalAmount:e.target.value})} required/></label><label>יתרה נוכחית<input type="number" min="0" value={form.outstandingAmount} onChange={e=>setForm({...form,outstandingAmount:e.target.value})}/></label><label>ריבית %<input type="number" min="0" step="0.01" value={form.interestRate} onChange={e=>setForm({...form,interestRate:e.target.value})}/></label><label>החזר חודשי<input type="number" min="0" value={form.monthlyPayment} onChange={e=>setForm({...form,monthlyPayment:e.target.value})}/></label><label>התחלה<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>סיום<input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><button className="primary-button">הוסף הלוואה</button></form></div></section></main> }
