use client';
import {useEffect,useState} from "react";
type M={id:string;type:"CASH"|"CARD"|"BANK_ACCOUNT"|"OTHER";nickname:string;institution:string|null;last4:string|null};
export default function Settings(){
 const [rows,setRows]=useState<M[]>([]),[form,setForm]=useState<any>({type:"CARD",nickname:"",institution:"",last4:""}),[error,setError]=useState("");
 async function load(){setRows(await (await fetch("/api/payment-methods")).json())};useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/payment-methods",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!r.ok){setError((await r.json()).error||"שגיאה");return}setForm({type:"CARD",nickname:"",institution:"",last4:""});load()}
 async function remove(id:string){if(confirm("למחוק את אמצעי התשלום?")){await fetch(`/api/payment-methods/${id}`,{method:"DELETE"});load()}}
 return <div><h1 className="text-3xl font-black mb-1">הגדרות</h1><p className="text-gray-500 mb-6">אמצעי תשלום ופרטים כלליים</p>
 <section className="bg-white rounded-2xl border p-5 mb-6"><h2 className="font-bold text-lg mb-4">הוספת אמצעי תשלום</h2><p className="text-sm text-gray-500 mb-4">המערכת שומרת רק כינוי, מוסד ו-4 ספרות אחרונות. לעולם אין להזין כאן מספר כרטיס מלא, CVV או תוקף.</p><form onSubmit={save} className="grid md:grid-cols-4 gap-3"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="border rounded-xl p-3"><option value="CARD">כרטיס</option><option value="BANK_ACCOUNT">חשבון בנק</option><option value="CASH">מזומן</option><option value="OTHER">אחר</option></select><input required value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})} placeholder="כינוי" className="border rounded-xl p-3"/><input value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})} placeholder="מוסד" className="border rounded-xl p-3"/>{(form.type==="CARD"||form.type==="BANK_ACCOUNT")&&<input required maxLength={4} pattern="\\d{4}" inputMode="numeric" value={form.last4} onChange={e=>setForm({...form,last4:e.target.value.replace(/\\D/g,"").slice(0,4)})} placeholder="4 ספרות אחרונות" className="border rounded-xl p-3" dir="ltr"/>}<button className="bg-gray-900 text-white rounded-xl px-4 py-3 md:col-span-4">הוספה</button>{error&&<div className="text-red-600 md:col-span-4">{error}</div>}</form></section>
 <section className="bg-white rounded-2xl border p-5"><h2 className="font-bold text-lg mb-4">אמצעי תשלום שמורים</h2><div className="space-y-3">{rows.map(m=><div key={m.id} className="flex justify-between items-center border rounded-xl p-4"><div><b>{m.nickname}</b><div className="text-sm text-gray-500">{m.institution||"—"} {m.last4?`· •••• ${m.last4}`:""}</div></div><button onClick={()=>remove(m.id)} className="text-red-600">מחיקה</button></div>)}</div></section>
 </div>
}
