"use client";
import {useEffect,useState} from "react";
type M={id:string;type:"CASH"|"CARD"|"BANK_ACCOUNT"|"OTHER";nickname:string;institution:string|null;last4:string|null};
const initial=()=>({type:"CARD",nickname:"",institution:"",last4:""});
export default function Settings(){
 const [rows,setRows]=useState<M[]>([]),[form,setForm]=useState<any>(initial()),[error,setError]=useState(""),[busy,setBusy]=useState(false),[householdSize,setHouseholdSize]=useState(1),[householdBusy,setHouseholdBusy]=useState(false);
 async function load(){const r=await fetch("/api/payment-methods");const d=await r.json();if(!r.ok)throw new Error(d.error||"לא ניתן לטעון");setRows(d)}
 async function loadHousehold(){const r=await fetch("/api/settings");const d=await r.json();if(!r.ok)throw new Error(d.error||"לא ניתן לטעון הגדרות");setHouseholdSize(d.householdSize)}
 useEffect(()=>{Promise.all([load(),loadHousehold()]).catch(e=>setError(e.message))},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setError("");setBusy(true);try{const r=await fetch("/api/payment-methods",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,last4:form.type==="CASH"?null:form.last4})});const d=await r.json();if(!r.ok)throw new Error(d.error||"שגיאה");setForm(initial());await load()}catch(e){setError(e instanceof Error?e.message:"שגיאה")}finally{setBusy(false)}}
 async function saveHousehold(e:React.FormEvent){e.preventDefault();setHouseholdBusy(true);setError("");try{const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({householdSize})});const d=await r.json();if(!r.ok)throw new Error(d.error||"שגיאה");setHouseholdSize(d.householdSize)}catch(e){setError(e instanceof Error?e.message:"שגיאה")}finally{setHouseholdBusy(false)}}
 async function remove(id:string){if(!confirm("למחוק את אמצעי התשלום?"))return;const r=await fetch(`/api/payment-methods/${id}`,{method:"DELETE"});if(!r.ok)setError("לא ניתן למחוק");else await load()}
 return <div><h1 className="text-3xl font-black mb-1">הגדרות</h1><p className="text-gray-500 mb-6">אמצעי תשלום, גודל משק הבית ופרטים כלליים</p><section className="bg-white rounded-2xl border p-5 mb-6"><h2 className="font-bold text-lg mb-2">גודל משק הבית</h2><p className="text-sm text-gray-500 mb-4">הנתון משמש את מנגנון התקציב כדי לנרמל הוצאות לנפש. המלצה לא תתבסס על ממוצע בלבד.</p><form onSubmit={saveHousehold} className="flex flex-wrap items-end gap-3"><label className="block"><span className="block text-sm font-semibold mb-1">מספר נפשות</span><input required min={1} max={20} type="number" value={householdSize} onChange={e=>setHouseholdSize(Math.max(1,Math.min(20,Number(e.target.value)||1)))} className="border rounded-xl p-3 w-32"/></label><button disabled={householdBusy} className="primary-button disabled:opacity-50">{householdBusy?"שומר...":"שמירת גודל משק הבית"}</button></form></section><section className="bg-white rounded-2xl border p-5 mb-6"><h2 className="font-bold text-lg mb-4">הוספת אמצעי תשלום</h2><p className="text-sm text-gray-500 mb-4">המערכת שומרת רק כינוי, מוסד ו-4 ספרות אחרונות. לעולם אין להזין כאן מספר כרטיס מלא, CVV או תוקף.</p><form onSubmit={save} className="grid md:grid-cols-4 gap-3"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value,last4:""})} className="border rounded-xl p-3"><option value="CARD">כרטיס</option><option value="BANK_ACCOUNT">חשבון בנק</option><option value="CASH">מזומן</option><option value="OTHER">אחר</option></select><input required maxLength={80} value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})} placeholder="כינוי" className="border rounded-xl p-3"/><input maxLength={100} value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})} placeholder="מוסד" className="border rounded-xl p-3"/>{(form.type==="CARD"||form.type==="BANK_ACCOUNT")&&<input required maxLength={4} pattern="\d{4}" inputMode="numeric" value={form.last4} onChange={e=>setForm({...form,last4:e.target.value.replace(/\D/g,"").slice(0,4)})} placeholder="4 ספרות אחרונות" className="border rounded-xl p-3" dir="ltr"/>}<button disabled={busy} className="primary-button md:col-span-4 disabled:opacity-50">{busy?"שומר...":"הוספה"}</button>{error&&<div role="alert" className="text-red-600 md:col-span-4">{error}</div>}</form></section><section className="bg-white rounded-2xl border p-5"><h2 className="font-bold text-lg mb-4">אמצעי תשלום שמורים</h2><div className="space-y-3">{rows.map(m=><div key={m.id} className="flex justify-between items-center border rounded-xl p-4"><div><b>{m.nickname}</b><div className="text-sm text-gray-500">{m.institution||"—"} {m.last4?`· •••• ${m.last4}`:""}</div></div><button onClick={()=>remove(m.id)} className="text-red-600">מחיקה</button></div>)}</div>{rows.length===0&&<p className="text-gray-500">אין אמצעי תשלום שמורים.</p>}</section></div>
}
