"use client";
import { useState } from "react";
import Link from "next/link";

type Result = { rowsImported: number; rowsUpdated: number; rowsSkipped: number; alreadyProcessed?: boolean };
type FileState = { file: File; hash: string; duplicate: boolean; status: "חדש" | "כבר יובא" | "מייבא" | "הושלם" | "שגיאה"; message?: string; result?: Result };
const MAX_FILE_BYTES = 10 * 1024 * 1024;
const MAX_OCR_PAGES = 30;
async function fileHash(file: File) { const bytes = new Uint8Array(await file.arrayBuffer()); const prefix = new TextEncoder().encode("CREDIT_CARD_PDF:"); const data = new Uint8Array(prefix.length + bytes.length); data.set(prefix); data.set(bytes, prefix.length); const digest = await crypto.subtle.digest("SHA-256", data); return Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, "0")).join(""); }
async function readResponse(response: Response) { const text = await response.text(); if (!text.trim()) throw new Error(`השרת החזיר תשובה ריקה (HTTP ${response.status})`); if (!response.headers.get("content-type")?.includes("application/json")) throw new Error("השרת החזיר תשובה לא צפויה."); return JSON.parse(text) as Record<string, any>; }
async function extractPdfTextLocally(file: File, onProgress: (message: string) => void) {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); const data = new Uint8Array(await file.arrayBuffer()); const pdf = await pdfjs.getDocument({ data, useWorkerFetch: false }).promise;
  if (pdf.numPages > MAX_OCR_PAGES) throw new Error(`ה-PDF מכיל ${pdf.numPages} עמודים. ניתן לבצע OCR עד ${MAX_OCR_PAGES} עמודים בכל קובץ.`);
  const { createWorker } = await import("tesseract.js"); const worker = await createWorker("heb+eng", 1, { logger: m => { if (typeof m?.progress === "number") onProgress(`OCR: ${Math.round(m.progress * 100)}%`); } });
  try { const chunks: string[] = []; for (let n = 1; n <= pdf.numPages; n++) { onProgress(`OCR מקומי: עמוד ${n} מתוך ${pdf.numPages}`); const page = await pdf.getPage(n); const viewport = page.getViewport({ scale: 2 }); const canvas = document.createElement("canvas"); canvas.width = Math.ceil(viewport.width); canvas.height = Math.ceil(viewport.height); const ctx = canvas.getContext("2d", { willReadFrequently: true }); if (!ctx) throw new Error("הדפדפן לא אפשר יצירת משטח OCR"); await page.render({ canvasContext: ctx, canvas, viewport }).promise; const result = await worker.recognize(canvas); chunks.push(`--- PAGE ${n} ---\n${result.data.text}`); canvas.width = 1; canvas.height = 1; page.cleanup(); } return chunks.join("\n\n"); } finally { await worker.terminate(); }
}
export default function CreditCardPdfImportPage() {
  const [items, setItems] = useState<FileState[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState(""), [progress, setProgress] = useState("");
  const choose = async (list: FileList | null) => { if (!list?.length) return; setError(""); setProgress("מחשב טביעת אצבע מקומית ובודק כפילויות לפני העלאה…"); const selected = Array.from(list).slice(0, 50); const bad = selected.find(f => !/\.pdf$/i.test(f.name) || f.size > MAX_FILE_BYTES); if (bad) { setError(`הקובץ "${bad.name}" אינו PDF תקין או גדול מ-10MB.`); setProgress(""); return; } try { const prepared = await Promise.all(selected.map(async file => ({ file, hash: await fileHash(file), duplicate: false, status: "חדש" as const }))); const res = await fetch("/api/import/credit-card-pdf", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ mode: "check", hashes: prepared.map(x => x.hash) }), cache: "no-store" }); const data = await readResponse(res); if (!res.ok) throw new Error(data.error || "לא ניתן לבדוק כפילויות"); const known = new Set((data.files || []).map((x: any) => x.hash)); setItems(prepared.map(x => known.has(x.hash) ? { ...x, duplicate: true, status: "כבר יובא" } : x)); } catch (e) { setError(e instanceof Error ? e.message : "לא ניתן לבדוק את הקבצים"); } finally { setProgress(""); } };
  const update = (i: number, patch: Partial<FileState>) => setItems(current => current.map((x, n) => n === i ? { ...x, ...patch } : x));
  const importOne = async (item: FileState, index: number) => { update(index, { status: "מייבא", message: undefined }); try { const fd = new FormData(); fd.append("file", item.file); const res = await fetch("/api/import/credit-card-pdf", { method: "POST", body: fd, headers: { Accept: "application/json" }, cache: "no-store" }); const data = await readResponse(res); if (res.ok) { update(index, { status: data.alreadyProcessed ? "כבר יובא" : "הושלם", duplicate: !!data.alreadyProcessed, result: data }); return; } if (res.status !== 422 || typeof data.error !== "string" || !data.error.includes("סרוק")) throw new Error(data.error || "הייבוא נכשל"); setProgress(`מבצע OCR מקומי עבור ${item.file.name} — הקובץ לא נשלח לשרת לצורך OCR.`); const text = await extractPdfTextLocally(item.file, setProgress); if (!text.trim()) throw new Error("לא הצלחנו לזהות טקסט מהסריקה."); const ocr = await fetch("/api/import/credit-card-pdf/text", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ text }), cache: "no-store" }); const ocrData = await readResponse(ocr); if (!ocr.ok) throw new Error(ocrData.error || "ייבוא ה-OCR נכשל"); update(index, { status: ocrData.alreadyProcessed ? "כבר יובא" : "הושלם", duplicate: !!ocrData.alreadyProcessed, result: ocrData }); } catch (e) { update(index, { status: "שגיאה", message: e instanceof Error ? e.message : "אירעה שגיאה" }); } };
  const importAll = async () => { if (busy) return; setBusy(true); setError(""); try { for (let i = 0; i < items.length; i++) { const item = items[i]; if (item.duplicate || item.status === "הושלם") continue; await importOne(item, i); } } finally { setBusy(false); setProgress(""); } };
  const duplicates = items.filter(x => x.duplicate).length, pending = items.filter(x => !x.duplicate && x.status !== "הושלם").length;
  return <div className="space-y-6">
    <header className="page-header"><div><div className="eyebrow">ייבוא אשראי</div><h1 className="page-title">ייבוא פירוטי אשראי מ-PDF</h1><p className="page-subtitle">בחר קובץ אחד או כמה קבצים יחד. לפני העלאה נבדק מקומית האם הקובץ כבר יובא, כך שאפשר לוודא מראש שלא תיווצר כפילות.</p></div><Link href="/import" className="secondary-button inline-flex">חזרה למסך הייבוא</Link></header>
    <section className="card-elevated p-5 md:p-8"><div className="rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/50 p-8 text-center md:p-12"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-50 text-3xl">📄</div><h2 className="mt-5 text-xl font-extrabold text-slate-900">בחירת פירוטי אשראי</h2><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-slate-500">עד 50 קבצי PDF בכל בחירה, עד 10MB לכל קובץ.</p><label className="primary-button mt-6 inline-flex cursor-pointer">בחירת קבצי PDF<input hidden type="file" multiple accept="application/pdf,.pdf" onChange={e => void choose(e.target.files)} /></label></div></section>
    {progress && <div role="status" className="rounded-xl bg-indigo-50 p-3 text-sm font-medium text-indigo-800">{progress}</div>}{error && <div role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{error}</div>}
    {items.length > 0 && <section className="card-elevated overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 bg-slate-50/70 px-5 py-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold text-slate-900">בדיקת קבצים לפני ייבוא</h2><p className="mt-1 text-xs text-slate-500">{items.length} קבצים · {duplicates} כבר יובאו · {pending} ממתינים לייבוא</p></div><button disabled={busy || pending === 0} onClick={() => void importAll()} className="primary-button disabled:opacity-50">{busy ? "מייבא קבצים…" : `ייבוא ${pending} קבצים חדשים`}</button></div><div className="divide-y divide-slate-100">{items.map((item, i) => <div key={`${item.hash}-${i}`} className="flex flex-col gap-2 px-5 py-4 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><div className="truncate font-semibold text-slate-900">{item.file.name}</div><div className="mt-1 text-xs text-slate-500">{(item.file.size / 1024).toFixed(0)} KB · {item.status === "כבר יובא" ? "המסמך כבר יובא בעבר — לא יועלה שוב" : item.status === "הושלם" ? `${item.result?.rowsImported || 0} נוספו · ${item.result?.rowsUpdated || 0} עודכנו` : item.message || "חדש — מוכן לייבוא"}</div></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status === "כבר יובא" ? "bg-amber-50 text-amber-700" : item.status === "שגיאה" ? "bg-red-50 text-red-700" : item.status === "הושלם" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-700"}`}>{item.status}</span></div>)}</div></section>}
    <aside className="card-elevated p-6"><h2 className="font-bold text-slate-900">🔒 פרטיות וכפילויות</h2><div className="mt-5 space-y-3 text-sm text-slate-700"><div>✓ לפני העלאה נשלחת לשרת רק טביעת SHA-256 של הקובץ לצורך בדיקת כפילות</div><div>✓ PDF רגיל: הטקסט עובר ניקוי לפני Gemini</div><div>✓ PDF סרוק: התמונה נשארת בדפדפן וה-OCR מתבצע מקומית</div><div>✓ מספרי כרטיס וחשבון, CVV, תעודת זהות, טלפון ודוא״ל מוסרים לפני Gemini</div><div>✓ ה-PDF המקורי לא נשמר ב-DB</div><div>✓ השרת בודק שוב את הקובץ בזמן הייבוא, בנוסף לבדיקה המקדימה</div></div></aside>
  </div>;
}
