"use client";
import { useState } from "react";
import Link from "next/link";

type Result = { rowsImported: number; rowsUpdated: number; rowsSkipped: number; pages?: number; alreadyProcessed?: boolean };
const MAX_FILE_BYTES = 10 * 1024 * 1024;

async function readResponse(response: Response) { const text = await response.text(); const contentType = response.headers.get("content-type") ?? ""; if (!text.trim()) throw new Error(`השרת החזיר תשובה ריקה (HTTP ${response.status})`); if (!contentType.includes("application/json")) throw new Error("השרת החזיר תשובה לא צפויה."); return JSON.parse(text) as Record<string, unknown>; }

export default function CreditCardPdfImportPage() {
  const [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [result, setResult] = useState<Result | null>(null);
  const choose = (value: File | null) => { setError(""); setResult(null); if (!value) return setFile(null); if (!/\.pdf$/i.test(value.name)) return setError("ניתן להעלות רק קובץ PDF"); if (value.size > MAX_FILE_BYTES) return setError("הקובץ גדול מדי (מקסימום 10MB)"); setFile(value); };
  const submit = async () => { if (!file) return; setBusy(true); setError(""); try { const fd = new FormData(); fd.append("file", file); const response = await fetch("/api/import/credit-card-pdf", { method: "POST", body: fd, headers: { Accept: "application/json" }, cache: "no-store" }); const data = await readResponse(response); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "הייבוא נכשל"); setResult(data as unknown as Result); } catch (e) { setError(e instanceof Error ? e.message : "אירעה שגיאה"); } finally { setBusy(false); } };
  return <div className="space-y-6">
    <header className="page-header"><div><div className="eyebrow">ייבוא אשראי</div><h1 className="page-title">ייבוא פירוט אשראי מ-PDF</h1><p className="page-subtitle">ה-PDF מפוענח מקומית, מידע רגיש מנוקה, ורק הטקסט הנדרש לניתוח נשלח ל-Gemini.</p></div><Link href="/import" className="secondary-button inline-flex items-center justify-center">חזרה לייבוא</Link></header>
    {result ? <section className="card-elevated p-6 text-center md:p-10"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-50 text-3xl text-emerald-600">✓</div><div className="eyebrow mt-5">{result.alreadyProcessed ? "הקובץ כבר עובד" : "הייבוא הושלם"}</div><h2 className="mt-2 text-2xl font-extrabold text-slate-900">{result.alreadyProcessed ? "לא נוצרו כפילויות" : "עסקאות האשראי נשמרו"}</h2><p className="mt-2 text-sm text-slate-500">{result.rowsImported} נוספו · {result.rowsUpdated} עודכנו · {result.rowsSkipped} דולגו{result.pages ? ` · ${result.pages} עמודים` : ""}</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/credit-card-transactions" className="primary-button">צפה בעסקאות האשראי</Link><button onClick={() => { setFile(null); setResult(null); }} className="secondary-button">ייבוא נוסף</button></div></section> : <div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="card-elevated p-5 md:p-8"><div className="rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50/50 p-8 text-center md:p-12"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-50 text-3xl">📄</div><h2 className="mt-5 text-xl font-extrabold text-slate-900">העלה פירוט אשראי PDF</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">המערכת תחזיר עסקאות, תשלומים והחזרים ליומן כרטיס האשראי. ה-PDF עצמו אינו נשלח ל-Gemini.</p><label className="primary-button mt-6 inline-flex cursor-pointer">בחירת PDF<input hidden type="file" accept="application/pdf,.pdf" onChange={e => choose(e.target.files?.[0] || null)} /></label><div className="mt-4 text-xs text-slate-400">PDF · עד 10MB</div>{file && <div className="mx-auto mt-6 max-w-lg rounded-2xl border bg-white p-4 text-right"><b className="block truncate text-sm">{file.name}</b><span className="text-xs text-slate-500">{(file.size / 1024).toFixed(0)} KB</span></div>}{error && <div role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{error}</div>}{file && <button disabled={busy} onClick={submit} className="primary-button mt-5 w-full disabled:opacity-60">{busy ? "מחלץ ומנתח…" : "נתח והעלה"}</button>}</div></section><aside className="card-elevated p-6"><h2 className="font-bold text-slate-900">🔒 פרטיות לפני הכול</h2><div className="mt-5 space-y-3 text-sm text-slate-700"><div>✓ חילוץ PDF מתבצע בשרת שלך</div><div>✓ מספרי כרטיס וחשבון מוסרים לפני Gemini</div><div>✓ CVV וקודים מוסרים</div><div>✓ תעודת זהות, טלפון ודוא״ל מוסרים</div><div>✓ Gemini מקבל טקסט מנוקה בלבד</div><div>✓ ה-PDF המקורי לא נשמר ב-DB</div><div>✓ הייבוא מוגן מפני כפילויות</div></div><div className="mt-6 rounded-2xl border border-amber-100 bg-amber-50 p-4 text-xs leading-5 text-amber-800">בגרסה הזו PDF חייב להכיל טקסט שניתן לחלץ. PDF שהוא סריקה/תמונה בלבד יזוהה ויידחה בלי לשלוח את התמונה ל-Gemini.</div></aside></div>}
  </div>;
}
